import type { ComponentType, SVGProps } from 'react';

import {
  Anchor,
  Axe,
  Backpack,
  Bird,
  Bomb,
  BookOpen,
  Bot,
  Bug,
  ChevronDown,
  ChevronUp,
  Church,
  Circle,
  CircleDashed,
  CircleDot,
  Coins,
  Crown,
  Diamond,
  Drama,
  Droplets,
  Eclipse,
  Eye,
  Flame,
  FlaskConical,
  Gem,
  Globe,
  Hammer,
  Heart,
  Hexagon,
  Key,
  KeyRound,
  Landmark,
  Leaf,
  Link2,
  Loader,
  Magnet,
  Map,
  MessageSquare,
  Moon,
  MoonStar,
  Mountain,
  Orbit,
  Package,
  Rainbow,
  RotateCcw,
  ScrollText,
  Shield,
  ShieldCheck,
  ShieldHalf,
  Skull,
  Snowflake,
  Sparkle,
  Sparkles,
  Star,
  Sun,
  SunDim,
  Sword,
  Swords,
  Target,
  Tent,
  TestTube2,
  TreePine,
  TriangleAlert,
  User,
  UserPlus,
  UserRound,
  Wand2,
  Waves,
  Wheat,
  Wind,
  Wrench,
  Zap,
} from 'lucide-react';

import {
  BatIcon,
  BearIcon,
  BoarIcon,
  BookIcon,
  CastleIcon,
  DemonIcon,
  DesertIcon,
  DragonIcon,
  EagleIcon,
  ElfIcon,
  FairyIcon,
  ForgeIcon,
  FoxIcon,
  GhostIcon,
  HauntedHouseIcon,
  HoleIcon,
  LionIcon,
  MonsterIcon,
  NinjaIcon,
  OwlIcon,
  RockIcon,
  ScorpionIcon,
  SnakeIcon,
  SpiderIcon,
  VolcanoIcon,
  VampireIcon,
  WolfIcon,
  ZombieIcon,
} from '@/components/icons/FeatureIcons';

type IconComponent = ComponentType<SVGProps<SVGSVGElement>>;

export const ICON_REGISTRY: Record<string, IconComponent> = {
  /* ── Lucide icons ── */
  anchor: Anchor,
  axe: Axe,
  backpack: Backpack,
  bird: Bird,
  bomb: Bomb,
  'book-open': BookOpen,
  bot: Bot,
  bug: Bug,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  church: Church,
  circle: Circle,
  'circle-dashed': CircleDashed,
  'circle-dot': CircleDot,
  coins: Coins,
  crown: Crown,
  diamond: Diamond,
  drama: Drama,
  droplets: Droplets,
  eclipse: Eclipse,
  eye: Eye,
  flame: Flame,
  flask: FlaskConical,
  gem: Gem,
  globe: Globe,
  hammer: Hammer,
  heart: Heart,
  hexagon: Hexagon,
  key: Key,
  'key-round': KeyRound,
  landmark: Landmark,
  leaf: Leaf,
  link: Link2,
  loader: Loader,
  magnet: Magnet,
  map: Map,
  'message-square': MessageSquare,
  moon: Moon,
  'moon-star': MoonStar,
  mountain: Mountain,
  orbit: Orbit,
  package: Package,
  rainbow: Rainbow,
  'rotate-ccw': RotateCcw,
  'scroll-text': ScrollText,
  shield: Shield,
  'shield-check': ShieldCheck,
  'shield-half': ShieldHalf,
  skull: Skull,
  snowflake: Snowflake,
  sparkle: Sparkle,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  'sun-dim': SunDim,
  sword: Sword,
  swords: Swords,
  target: Target,
  tent: Tent,
  'test-tube': TestTube2,
  'tree-pine': TreePine,
  'triangle-alert': TriangleAlert,
  user: User,
  'user-plus': UserPlus,
  'user-round': UserRound,
  wand: Wand2,
  waves: Waves,
  wheat: Wheat,
  wind: Wind,
  wrench: Wrench,
  zap: Zap,

  /* ── Custom fantasy icons ── */
  bat: BatIcon,
  bear: BearIcon,
  boar: BoarIcon,
  book: BookIcon,
  castle: CastleIcon,
  demon: DemonIcon,
  desert: DesertIcon,
  dragon: DragonIcon,
  eagle: EagleIcon,
  elf: ElfIcon,
  fairy: FairyIcon,
  forge: ForgeIcon,
  fox: FoxIcon,
  ghost: GhostIcon,
  'haunted-house': HauntedHouseIcon,
  hole: HoleIcon,
  lion: LionIcon,
  monster: MonsterIcon,
  ninja: NinjaIcon,
  owl: OwlIcon,
  rock: RockIcon,
  scorpion: ScorpionIcon,
  snake: SnakeIcon,
  spider: SpiderIcon,
  vampire: VampireIcon,
  volcano: VolcanoIcon,
  wolf: WolfIcon,
  zombie: ZombieIcon,
};

/**
 * Maps legacy emoji strings (from saved data) to registry icon IDs.
 * Used at load time to migrate old emoji-based icon values.
 */
export const EMOJI_TO_ICON_ID: Record<string, string> = {
  '🌀': 'loader',
  '💥': 'bomb',
  '🔥': 'flame',
  '❄️': 'snowflake',
  '⚡': 'zap',
  '☠️': 'skull',
  '✨': 'sparkles',
  '🌿': 'leaf',
  '🛡': 'shield',
  '🛡️': 'shield',
  '👁': 'eye',
  '🌙': 'moon',
  '☀️': 'sun',
  '💀': 'skull',
  '🌪️': 'wind',
  '🩸': 'droplets',
  '🔮': 'orbit',
  '💫': 'sparkle',
  '🌊': 'waves',
  '⚙️': 'wrench',
  '🔩': 'wrench',
  '🪖': 'shield-half',
  '⛓️': 'link',
  '💎': 'gem',
  '🌟': 'star',
  '🦾': 'wrench',
  '🪬': 'hexagon',
  '🏛️': 'landmark',
  '🗡️': 'sword',
  '🔰': 'shield-check',
  '⚔️': 'swords',
  '🎒': 'backpack',
  '🧪': 'test-tube',
  '📜': 'scroll-text',
  '💍': 'circle-dot',
  '🕯️': 'flame',
  '🗝️': 'key-round',
  '📿': 'circle-dashed',
  '🧿': 'eye',
  '🪄': 'wand',
  '🎯': 'target',
  '🧲': 'magnet',
  '⚗️': 'flask',
  '🪙': 'coins',
  '🗺️': 'map',
  '🔑': 'key',
  '📦': 'package',
  '🏹': 'target',
  '🪓': 'axe',
  '🔱': 'anchor',
  '🔨': 'hammer',
  '🪃': 'rotate-ccw',
  '🦂': 'scorpion',
  '🐉': 'dragon',
  '🧙': 'wand',
  '🦅': 'eagle',
  '🐺': 'wolf',
  '🦁': 'lion',
  '🧝': 'elf',
  '👺': 'demon',
  '🧟': 'zombie',
  '🤖': 'bot',
  '🧚': 'fairy',
  '🐻': 'bear',
  '🦊': 'fox',
  '🦉': 'owl',
  '🐗': 'boar',
  '👤': 'user',
  '🧛': 'vampire',
  '🌈': 'rainbow',
  '🎭': 'drama',
  '🎪': 'tent',
  '👹': 'demon',
  '🕷️': 'spider',
  '🐍': 'snake',
  '🦇': 'bat',
  '👻': 'ghost',
  '🌑': 'eclipse',
  '🧑': 'user-round',
  '🧑‍🌾': 'user-round',
  '🧑‍🔬': 'user-round',
  '🧑‍⚕️': 'user-round',
  '🧑‍🎨': 'user-round',
  '🧑‍🍳': 'user-round',
  '🧑‍🏫': 'user-round',
  '🧑‍⚖️': 'user-round',
  '🧑‍✈️': 'user-round',
  '🥷': 'ninja',
  '🤴': 'crown',
  '👸': 'crown',
  '🌲': 'tree-pine',
  '🏔️': 'mountain',
  '🏰': 'castle',
  '🌋': 'volcano',
  '🏚️': 'haunted-house',
  '⛪': 'church',
  '🌾': 'wheat',
  '🏜️': 'desert',
  '🪨': 'rock',
  '🕳️': 'hole',
  '⚠️': 'triangle-alert',
  '📖': 'book-open',
  '🖤': 'moon',
};

/**
 * Resolve an icon value: if it's a registered icon ID, return it as-is;
 * if it's a legacy emoji, map it to the new icon ID; otherwise return as-is
 * (IconDisplay will render the raw string as fallback text).
 */
export function resolveIconId(value: string): string {
  if (ICON_REGISTRY[value]) return value;
  return EMOJI_TO_ICON_ID[value] ?? value;
}
